vagrantfile:
    private_network: 192.168.56.70
    box: ubuntu/trusty32
    box_url: ubuntu/trusty32
    hostname: php70x32
    memory: '1024'
    cpus: '1'
    docroot: /var/www/html
    composants:
        - php70
        - php-oci70x32
        - mysql
        - composer
        - adminer



