vagrantfile:
    hostname: php54x32
    box: precise32
    box_url: http://files.vagrantup.com/precise32.box
    memory: '1024'
    forwarded_port: '5854'
    cpus: '1'
    docroot: /var/www
    composants:
        - php54
        - php-oci54x32
        - mysql
        - composer
        - drush
        - adminer

