vagrantfile:
    private_network: 192.168.56.52
    hostname: php52x32
    box: precise32
    box_url: http://files.vagrantup.com/precise32.box
    memory: '1024'
    cpus: '1'
    docroot: /var/www
    synced_folder:
      f1:
        source: C:/Devapp/wamp/www/common-libs
        target: /srv/applic
    composants:
        - php52
        - php-oci52x32
        - php-apc52
        - mysql
        - composer
        - adminer

