vagrantfile:
    hostname: php52x32
    box: precise32
    box_url: http://files.vagrantup.com/precise32.box
    memory: '1024'
    cpus: '1'
    docroot: /var/www
    forwarded_port: '5852'
    synced_folder:
      f1:
        source: C:/Devapp/wamp/www/common-libs
        target: /srv/applic
    composants:
        - php52
        - php-oci52x32
#        - php-apc52   #ne semble pas 100% fiable
        - mysql
        - adminer
        - mailhog

