vagrantfile:
    box: hashicorp/precise32
    box_url: hashicorp/precise32
    hostname: php56x32
    memory: '1024'
    cpus: '1'
    composants:
      apache
      php56
      php5x32_oci
      composer
      adminer

