vagrantfile:
    hostname: php56x32
    box: ubuntu/trusty32
    box_url: ubuntu/trusty32
    memory: '1024'
    cpus: '1'
    forwarded_port: '5856'
    docroot: /var/www/html
    composants:
        - php56
        - php-oci56x32
        - mailhog2
        - mysql
        - composer
        - drush
        - adminer

