# -*- mode: ruby -*-
dir = File.dirname(File.expand_path(__FILE__))
require 'yaml'
require "../common/ruby/deep_merge.rb"
configValues = YAML.load_file("../common/config.yaml")

if File.file?("../common/config.yaml")
  custom = YAML.load_file("#{dir}/config.yaml")
  configValues.deep_merge!(custom)
end

data = configValues['vagrantfile']
Vagrant.require_version '>= 1.6.0'
eval File.read("../common/script/Vagrantfile-common")



