#docker build -t myphp /vagrant/scripts/myphp/ --rm
#docker run -d -p 80:80 --name my-running-app myphp
# or
#docker run -it -p 80:80 --name my-running-app myphp
#
#docker exec it myphp
FROM php:5.6-apache
COPY *.php /var/www/html/

